<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('plugins/bootstrap-5.0.2-dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('plugins/boxicons-master/css/boxicons.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body id="body-pd">
        <header class="header" id="header">
            <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
            <div class="header_img"> <a href="" class="nav-link"><i class="bx bx-user-check"></i></a> </div>
        </header>
        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div> 
                    <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">BBBootstrap</span> </a>
                    <div class="nav_list">
                         <a href="#" class="nav_link active"> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Dashboard</span> </a>
                         <a href="#" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users</span> </a> 
                         <a href="#" class="nav_link"> <i class='bx bx-message-square-detail nav_icon'></i> <span class="nav_name">Messages</span> </a>
                         <a href="#" class="nav_link"> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Bookmark</span> </a>
                         <a href="#" class="nav_link"> <i class='bx bx-folder nav_icon'></i> <span class="nav_name">Files</span> </a>
                         <a href="#" class="nav_link"> <i class='bx bx-cog nav_icon'></i> <span class="nav_name">Parametres</span> </a>
                    </div>
                </div> 
                <a href="#" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>
            </nav>
        </div>
        <!--Container Main start-->
        <div class="height-100 bg-light">
           <?= $this->content ?>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('plugins/bootstrap-5.0.2-dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('plugins/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) 
            ->prependFile($this->basePath('js/layout.js'))
            ?>
    </body>
</html>

